// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY_HedZyipoZFIhx-5moLh5KtLJXD1w5o',
    appId: '1:769412542471:web:ee9dddf91adfbaf0a37aa2',
    messagingSenderId: '769412542471',
    projectId: 'biomarkapp-da4b3',
    authDomain: 'biomarkapp-da4b3.firebaseapp.com',
    storageBucket: 'biomarkapp-da4b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA96eT1pJ3IIIW4y8VaaB2ibGf2RcS87os',
    appId: '1:769412542471:android:803c9a3f5124018da37aa2',
    messagingSenderId: '769412542471',
    projectId: 'biomarkapp-da4b3',
    storageBucket: 'biomarkapp-da4b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP0ehqQEG3Q3j-i_fa5OSHCVK1-0OZ98E',
    appId: '1:769412542471:ios:c88c68297eb243b3a37aa2',
    messagingSenderId: '769412542471',
    projectId: 'biomarkapp-da4b3',
    storageBucket: 'biomarkapp-da4b3.firebasestorage.app',
    iosBundleId: 'com.example.biomark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP0ehqQEG3Q3j-i_fa5OSHCVK1-0OZ98E',
    appId: '1:769412542471:ios:c88c68297eb243b3a37aa2',
    messagingSenderId: '769412542471',
    projectId: 'biomarkapp-da4b3',
    storageBucket: 'biomarkapp-da4b3.firebasestorage.app',
    iosBundleId: 'com.example.biomark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY_HedZyipoZFIhx-5moLh5KtLJXD1w5o',
    appId: '1:769412542471:web:800f137fff091523a37aa2',
    messagingSenderId: '769412542471',
    projectId: 'biomarkapp-da4b3',
    authDomain: 'biomarkapp-da4b3.firebaseapp.com',
    storageBucket: 'biomarkapp-da4b3.firebasestorage.app',
  );
}
